select
	eventParticipate.id,
	eventParticipate.contactId,
	eventParticipate.eventId,
	eventParticipate.eventDate,
	eventParticipate.state,
	eventParticipate.reason,
	eventParticipate.modifiedAt,
	event.endDate,
	event.locationId,
	event.maxParticipants,
	event.price,
	event.startDate,
	event.text,
	event.type,
	event.visibility
FROM
	EventParticipate eventParticipate left join Event event on event.id=eventParticipate.eventId
WHERE
	{search}