select
	eventParticipate.id,
	eventParticipate.contactId,
	eventParticipate.eventId,
	eventParticipate.eventDate,
	eventParticipate.state,
	eventParticipate.reason,
	eventParticipate.modifiedAt,
	event.category,
	event.id,
	event.startDate,
	event.endDate,
	event.contactId,
	event.locationId,
	event.marketingEvent,
	event.maxParticipants,
	event.confirm,
	event.price,
	event.visibility,
	event.text,
	event.type,
	event.price,
	contact.age,
	contact.aboutMe,
	contact.attr,
	contact.attrEx,
	contact.attr0,
	contact.attr0Ex,
	contact.attr1,
	contact.attr1Ex,
	contact.attr2,
	contact.attr2Ex,
	contact.attr3,
	contact.attr3Ex,
	contact.attr4,
	contact.attr4Ex,
	contact.attr5,
	contact.attr5Ex,
	contact.attrInterest,
	contact.attrInterestEx,
	contact.birthday,
	contact.birthdayDisplay,
	contact.gender,
	contact.guide,
	contact.id,
	contact.imageList,
	contact.latitude,
	contact.longitude,
	contact.pseudonym,
	contactLink.contactId,
	contactLink.contactId2,
	contactLink.id,
	contactLink.status,
	'' as geolocationDistance
FROM
	EventParticipate eventParticipate,
	Event event,
	Contact contact
	left join ContactLink contactLink on
		contactLink.contactId={USERID} and contactLink.contactId2=contact.id
	or
		contactLink.contactId2={USERID} and contactLink.contactId=contact.id
WHERE
	event.id=eventParticipate.eventId and
	eventParticipate.contactId=contact.id and
	{search}